### ISSUE TITLE
[feature add] Creating faq.json file with question & answers

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [PiyushKalyanpy/GyanaGuru#208]
I'm willing to add `faq.json`  file in `./data/ ` folder 

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/96011814/16ee525d-afb5-46c5-94b2-1c71dc5ce1f9)

### Please __Assign this issue__ to me with __GSSoC23__ label
<hr>

## Tasks to do : 
- [x] Creating a faq.json file in the data folder
- [ ] Adding relevant questions
- [ ] Providing simpler answers addressing questions

**Comment by Aman-Singh-Kushwaha** [comment]
Thanks @PiyushKalyanpy for assigning, 

Also, I have started discussions for some FAQ questions by community
If you had any suggestions, please dump some questions over there

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
