### ISSUE TITLE
[NEW] : 🎨 Implementing new Dashboard Design

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#48]
Implement New Dashboard Design
## Description
We have a new and exciting dashboard design for our project that we would like to implement. The new design aims to enhance the user experience and provide a more intuitive and visually appealing interface. ( Design given below ⬇️ )

## Tasks
- [ ] Left Sidebar
     - [ ]  Logo with name
     - [ ] Menu options ( each option should be component)
     - [ ] Upgrade card
- [ ] Main Content
     - [ ] Search bar  (component)
     - [ ] Course Section
- [ ] Right Sidebar
     - [ ]  User profile ( component)

## Expected Outcome 
- You can make any single component like ( profile component, upgrade card, searchbar ) inside the ```components``` folder. 
- Make sure to add the state variable where required and also make required functions.

## Other Information
- Please code in - ```NEXT.js``` and ```Tailwind.css``` only (not in html, css, and js).
- Make sure to push you code in ```cache``` branch not in main branch for PR.

If you need any help, please feel free to ask! 
Let's create an impressive and user-friendly dashboard together! 🚀

## Design
![Design](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/fd9279e4-e4f6-4866-b265-e003612fc366)

**Comment by mani200307** [comment]
Can I work on this issue? Could you please assign me this under GSSoC'23 ?

**Comment by PiyushKalyanpy** [comment]
Assigning this task

**Comment by rhithesh** [comment]
hi I would want to work on this issue I will be trying to implement the left sidebar.

**Comment by PiyushKalyanpy** [comment]
@rhithesh  have you encountered a Firebase API key error? If so, how did you resolve it?

**Comment by rhithesh** [comment]
I resolved it by removing the if else statement in firebase.js. I have attached a picture.
![Screenshot 2023-05-21 094807](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115660976/cc5951e7-12f4-4769-a758-763dc93843ff)
base.js

**Comment by mani200307** [comment]
Okay, Then I'll work on the Main content and Right sidebar.

**Comment by rhithesh** [comment]
hi is there a figma file for the photo you posted thanks.

**Comment by PiyushKalyanpy** [comment]
> hi is there a figma file for the photo you posted thanks @PiyushKalyanpy .

Yes, I will make the Figma file public until tonight.

**Comment by kirtiraj22** [comment]
Hey @PiyushKalyanpy , I can help you build the admin panel. I have worked with Next.js in some of my projects. 

do let me know if the assigned contributor encounters any difficulties or is unable to make the required changes, I am available to take up the task and provide the necessary support. 
Please keep me informed if the need arises. 
Thank you!

**Comment by shreyal0007** [comment]
can i please contribute in this issue . Under the GSSOC 2023

**Comment by PiyushKalyanpy** [comment]
Sure I have assigned the task. You can divide the components.

**Comment by An525ish** [comment]
Hey, I would like to improve the 'Why choose us' section in terms of UI. As this look so dull.. I will add some better card  components and animations to make it look more appealing

https://github.com/PiyushKalyanpy/GyanaGuru/assets/93612051/79c4e05e-2343-46b3-921b-f5472a87f68c

-- card color and style will be adjusted according to the theme

**Comment by PiyushKalyanpy** [comment]
@An525ish Okay, you can go ahead.

**Comment by rhithesh** [comment]
@PiyushKalyanpy  hi can I have the figma file?

**Comment by Hariharanreddy** [comment]
Hi, I would like to optimize the search bar by using debouncing as that would reduce the number of API calls made to the server significantly. 

Can you assign that to me after the search bar is completed?

**Comment by PiyushKalyanpy** [comment]
@rhithesh  figma link - https://www.figma.com/file/TI8w4RDo857KrFiNiwnY2O/GSSoC'23---Gyanaguru?type=design&node-id=1%3A13&t=vVscFfvxiIlLx5xb-1

**Comment by PiyushKalyanpy** [comment]
@Hariharanreddy please create a new issue, i will assign you there.

**Comment by kirtiraj22** [comment]
hey @PiyushKalyanpy , as this task is assigned to multiple contributors, can we start a new discussion, so that we all can divide the tasks and work accordingly?

**Comment by Hariharanreddy** [comment]
> @Hariharanreddy please create a new issue, i will assign you there.

sure..

**Comment by muhammedanaskhan** [comment]
Can I work on this issue?

**Comment by shreyal0007** [comment]
@PiyushKalyanpy which component can i work on?

**Comment by shreyal0007** [comment]
can i pick up the search and all course section ?

**Comment by An525ish** [comment]
@PiyushKalyanpy I have completed the assigned work
Here is the link of discussion tab : https://github.com/PiyushKalyanpy/GyanaGuru/discussions/108#discussioncomment-5969661
Shall I send the PR now or shall I wait for others to complete the task coz there might be some merge conflicts thereafter...?

**Comment by shreyal0007** [comment]
@An525ish which component you have created so i can proceed accordingly.
