### ISSUE TITLE
[Feat]: FAQ Question and Answer Component

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#480]
### What feature?

The goal of this feature request is to design and implement a FAQ (Frequently Asked Questions) question and answer component. Please only accept this issue if you are able to complete all the tasks by July 17th, 2023, to prevent any conflicts.

Design and Implementaion : https://gyanaguru.vercel.app/design/faq

### Tasks to be done!

- [ ] I will complete the task by 17th July 2023.
- [x] Create a new Next.js functional component for the FAQ question and answer section in the components/cards folder.
- [x] Fetch the FAQ data from the faq.json file in the data directory.
- [x] Implement functionality to expand and collapse the questions when the user clicks on the plus (+) and minus (-) buttons.
- [ ] Test the component thoroughly to ensure proper functionality and responsiveness.
- [ ] Render that single component on the faq page for testing.
- [ ] Add a border on top.
- [ ] The components should take a single prop which will contain a JSON object for question and answer and then destructure it in the component file.

### Points to remember
- [ ] Design the component layout based on the provided design file.
- [ ] Use the Tailwind CSS framework to style the FAQ component.
- [ ] Integrate the Material-Symbols library for icons used in the component.
- [ ] The colours should be used from the given implementation file.

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/2450f76d-d4b3-41d7-9065-a574da4010f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by lalitkumawat1m** [comment]
Hey @PiyushKalyanpy,
I want to work on this issue ? as a GSSoC'23 contributor

**Comment by PiyushKalyanpy** [comment]
Ok, just make the 1 component which is marked in the green border and make sure to follow the guidelines and tasks.

**Comment by s2sharpit** [comment]
Thanks @PiyushKalyanpy for assigning the issue. ☺️

**Comment by s2sharpit** [comment]
Hi @PiyushKalyanpy,
Could you kindly share the data containing all the questions and answers with me? I currently don't have access to it. Thanks!

**Comment by PiyushKalyanpy** [comment]
use sample questions for now , i will update them later
