### ISSUE TITLE
[Feat]: Frontend  : About us page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#489]
### What feature?

Design and Implementaion : https://gyanaguru.vercel.app/design/about

### Tasks to be done!

- [ ] I will complete the task by 21th July 2023.
- [ ] Create separate component for the cards for about us page in components/cards folder
- [ ] Test the component thoroughly to ensure proper functionality and responsiveness.
- [ ] The components should take a single prop which will contain a JSON object for icons in string format and title for cards and then destructure it in the component file.

### Points to remember
- [ ] Design the component layout based on the provided design file.
- [ ] Use the Tailwind CSS framework to style the FAQ component.
- [ ] Integrate the Material-Symbols library for icons used in the component.
- [ ] The colours should be used from the given implementation file.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by anshulsoni4** [comment]
i wanted to work on this issue, i can complete this in a day
