### ISSUE TITLE
[Bug]: Enabling Dashboard page 

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#501]
## Task to do 

- [x] transfer the Contribution button file from `/components/depricated/Utils/ContributionButton` to `components/utils` folder.
- [x] Update the contribution button name to `CustomRedirectButton`
- [x] Remove the `disabled:true` field from dashboard json object from sidebar file in components folder to enable dashboard.
- [ ] #502

### Show us the trouble with screenshots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
I would work on this issue.
Please assign this to me under GSSOC'23

**Comment by lalitmee** [comment]
@s2sharpit, we have already assigned you three bugs. Please finish those first and then we can assign this to you.
