### ISSUE TITLE
[Bug]: Go to Dashboard page from login page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#503]
## Task to do

- [ ] Update the router route form `/courses` to `/dashboard` on the login page.

### Show us the trouble with screenshots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
I would work on this issue.
Please assign this to me under GSSOC'23

**Comment by lalitmee** [comment]
@s2sharpit, done.
