### ISSUE TITLE
[Bug]: Delete depricated folders and files.

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#504]
## Task to do 
- [ ] Make sure #501 and #502 are completed, then only start this task.

### Show us the trouble with screenshots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
I would work on this issue.
Please assign this to me under GSSOC'23

**Comment by lalitmee** [comment]
@s2sharpit, done.

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy, Can I work on it now?
