### ISSUE TITLE
[Bug]: Making AI card responsive

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#505]
## Task to do 

- [ ] making AI card responsive on the course page. 
- [ ] do not make a new card for small screen, adjust the text size for different screens.
- [ ] make sure to make small screen size the default first, then add the media queries for larger screens. 

### Guide 
- use only tailwind CSS.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/1bd96cc8-d413-4073-a4e4-d74af6e3ebd2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
I would work on this issue.
Please assign this to me under GSSOC'23

**Comment by PiyushKalyanpy** [comment]
Hi @s2sharpit , while I truly appreciate your contributions, I can't assign all the issues at once to avoid spam. It's essential to give other contributors a chance too. Feel free to work on any 1 issue.

**Comment by s2sharpit** [comment]
> Hi @s2sharpit , while I truly appreciate your contributions, I can't assign all the issues at once to avoid spam. It's essential to give other contributors a chance too. Feel free to work on any 1 issue.

Sure @PiyushKalyanpy, Please assign this issue then. I will work on this issue. 😊

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
The courses page is showing as loading from last 5 minutes. I'm not able to access it.
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104740281/23fc11cb-f3ef-45bf-b638-cee1516c2260)

**Comment by PiyushKalyanpy** [comment]
please check now

**Comment by s2sharpit** [comment]
> please check now, if still it is not working then try logout login

Ahh, It requires login to work.

I think there should be a message like "Please login first" and a button to redirect to the login page when the user tries to access the pages which require authentication.
What do you think @PiyushKalyanpy?

**Comment by PiyushKalyanpy** [comment]
@s2sharpit Ya! you are right, we are working on that issue and other login issues.
