### ISSUE TITLE
[Bug]: Call toast message for dark mode button

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#506]
## Task to do 
the dark mode button is not working now, so 

- [ ] add a toast message saying `Functionality removed due to bugs`
- [ ] use the showToast function and pass the message as an argument.
- [ ] use info as toast type.
- [ ] test the button on all the pages where dark mode button is already added.

already defined in components/util folder `showToast(message: string, type: "success" | "error" | "info"): JSX.Element`

### Show us the trouble with screenshots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
I would work on this issue.
Please assign this to me under GSSOC'23

**Comment by lalitmee** [comment]
@s2sharpit, done

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy, I would like to work on it.
