### ISSUE TITLE
[Bug]:  URL rewriting for static pages

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#507]
## Task to do 
static page like about us, faq are currently stored in the static folder and that file is rendered when `static/about` or `static/<file-name>` is called. But we want to call them without `static/` and to implement this follow the below steps : 

- [ ]  using the below reference rewrite the route for all the static pages from static to <file-name>
- [ ] update the route name in all the files where it /static/<file-name> is used.
- [ ] test all the file and button clicks.

Follow the rewrite next js documentation : https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites

### Show us the trouble with screenshots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by Vidip-Ghosh** [comment]
I would work on this issue. Please assign this to me under GSSOC'23
