### ISSUE TITLE
[Bug]: Remove signup text from login page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#510]
## Task to do

- [ ] Remove the signup text from the login page

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/56e8f630-c4d3-4903-99db-ddcbc1a511eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by Vidip-Ghosh** [comment]
I would like to work on this issue too.
